// tslint:disable
/**
 * Hakathon Swagger API
 * API for autogenerator
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {
    AdvertisementsApi,
    AdvertisementCategoriesApi,
    AnnouncementsApi,
    DiscussionTopicsApi,
    InitiativesApi,
    JwtLoginApi,
    MessagesApi,
    UserDevicesApi,
    UsersApi, ChatsApi,
} from './api';

export * from "./api";
export * from "./configuration";

export interface Api {
    login: JwtLoginApi
    users: UsersApi
    discussions: DiscussionTopicsApi
    messages: MessagesApi
    chats: ChatsApi
    announcements: AnnouncementsApi
    initiatives: InitiativesApi
    devices: UserDevicesApi
    advertisements: AdvertisementsApi
    advertisementCategories: AdvertisementCategoriesApi
}
